### ISSUE TITLE
Issues with requirements.txt 

### ISSUE THREAD

**Issue by gitihobo** [xaviviro/refacer#1]
Both CPU & GPU get multiple errors, from cuda installs to scikit-image refacer\lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll" How did I install? Made a conda env called it refacer then I git cloned inside it and installed requirements. So Env/Refacer/refacer

**Comment by xaviviro** [comment]
I would suggest taking a look at ONNX's documentation at this link: https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements. There you will find detailed information about the CUDA requirements and setup for use with ONNX Runtime.

**Comment by xaviviro** [comment]
If you don't have the necessary CUDA libraries, it should still work on CPU. Try the following commands:

``` bash
pip uninstall onnxruntime-gpu
pip install onnxruntime
```

**Comment by gitihobo** [comment]
is it possible to fix it instead of uninstalling? I installed both txt files, also heres more info [E:onnxruntime:Default, provider_bridge_ort.cc:1351 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1131 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load

**Comment by xaviviro** [comment]
You only need to install one of the requirement files. The difference between the two is that `onnxruntime` is for CPU, and `onnxruntime-gpu` is for GPU. **Ensure that you don't have both versions installed at the same time**. If you're having issues with GPU, you can opt for the CPU version.

**Comment by gitihobo** [comment]
reinstalled but I get this issue error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]

      *** Please install the `scikit-image` package (instead of `skimage`) ***

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by xaviviro** [comment]
Try with

`pip install scikit-image`

**Comment by xaviviro** [comment]
I just updated the requirements, changing 'skimage' to 'scikit-image'. It appears there was a mistake when creating the list. My apologies for the confusion. Please pull the latest version from the repository and try again. Let me know if you encounter any further issues!

**Comment by gitihobo** [comment]
Fixed, not sure if this is cached packages confusing my new environment but I got this issue now failed to load onnxruntime_providers_cuda.dll which I did install so maybe I need to install it manually? Its falling back to CPU even through I didnt install the requirements this time. also that possibly CoreMLExecutionProvider isnt supported in my environment, I installed python 3.10.9 so is there a reason? Im fine with manually fixing the issues if I need to, also I put inswapper_128.onnx inside the general folder next to app.py in case that matters

**Comment by xaviviro** [comment]
CoreMLExecutionProvider is intended for MacOSX only. If you're seeing a warning related to it, it's not an issue. It's just informing you that this specific feature may not be supported in your environment. Continue with your setup and let me know if you encounter any further issues.

**Comment by gitihobo** [comment]
Great but like I said I got this issue failed to load or find onnxruntime_providers_cuda.dll which I did install and is in the correct spot 2023-06-03 20:30:47.4078164 [E:onnxruntime:Default, provider_bridge_ort.cc:1351 onnxruntime::TryGetProviderInfo_CUDA] E:\e\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1131 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "E\MYPATH\envs\refacerr\lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

**Comment by xaviviro** [comment]
If you have the correct versions of CUDA and cuDNN, then please verify your environment variables.

Here is the guide for installing cuDNN on Windows: [NVIDIA cuDNN Install Guide](https://docs.nvidia.com/deeplearning/cudnn/install-guide/index.html#install-windows). It will help you to verify your installation and environment variables.

**Comment by gitihobo** [comment]
Can I install these only in the environment or are they forcefully general?

**Comment by xaviviro** [comment]
This generally gets installed and also depends on the driver for your Nvidia graphics card. If you can't get it to work, try using the CPU option as it also works well. I'm going to close this issue as, having solved the requirements issue thanks to you, this problem is not directly related to Refacer.

**Comment by gitihobo** [comment]
I cant seem to make it work for gpu, not sure how to do the installation process for proper cuda onix etc when inside a venv in anaconda

**Comment by xaviviro** [comment]
If you're having difficulties setting up the GPU on your machine, you can try out directly on Google Colab: [https://github.com/xaviviro/refacer/blob/main/notebooks/Refacer_colab.ipynb](https://github.com/xaviviro/refacer/blob/main/notebooks/Refacer_colab.ipynb)

**Comment by gitihobo** [comment]
Im a noob so I want to learn to troubleshoot this but I dont understand how to check requirements for onnx, my NVidia card is new enough to work, I installed this environment on a external drive with anaconda so I am not really sure how the add to path tip works here
