### ISSUE TITLE
Crashing after new updates..

### ISSUE THREAD

**Issue by azoksky** [xaviviro/refacer#10]
Now it takes awefully longer time to load and provide the link to UI. Evrything seems frozen and unresponsive.. To reconfirm, I did a fresh install but the result was no different. Attacching a video and environment path setup..
Gtx 1650ti 4gb.. 
It ran buttery smooth before the update. 

https://github.com/xaviviro/refacer/assets/62461404/59f1c7ef-1b53-43f6-9ce9-a47860fdbc05

![Screenshot 2023-06-06 154312](https://github.com/xaviviro/refacer/assets/62461404/b4cc4dca-61cf-4606-a781-1ade36c2ff01)

**Comment by xaviviro** [comment]
Thank you for reporting this issue and I apologize for any inconvenience caused.

It seems to be the same issue as #9.

**Comment by xaviviro** [comment]
https://github.com/xaviviro/refacer/issues/9#issuecomment-1578384346

**Comment by azoksky** [comment]
Ohhh that was so instant. Great work!!!!!!

**Comment by azoksky** [comment]
I tried after you fixed it... It took a minute to start extracting frame....which was unsual,...  Other than that, everything else is the same.. Thank you.. 
For some reason, Roop also has Tensorrt removed from the providers array. 
https://github.com/s0md3v/roop/blob/main/roop/globals.py

**Comment by xaviviro** [comment]
It's interesting what you mention about roop because in Colab with TensorrtExecutionProvider it runs incredibly fast, we will have to investigate why it works in Colab and not in Windows.
