### ISSUE TITLE
Error with refacer.py

### ISSUE THREAD

**Issue by zazazy** [xaviviro/refacer#17]
PS D:\refacer> python app.py
Traceback (most recent call last):
  File "D:\refacer\app.py", line 11, in <module>
    refacer = Refacer(force_cpu=args.force_cpu)
  File "D:\refacer\refacer.py", line 30, in __init__
    self.__check_encoders()
  File "D:\refacer\refacer.py", line 195, in __check_encoders
    commandout = subprocess.run(command, check=True, capture_output=True).stdout
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Не удается найти указанный файл

**Comment by xaviviro** [comment]
It seems that the problem is that you haven't properly installed ffmpeg or it isn't correctly set in your Windows PATH. You can check by typing ffmpeg into the terminal. If it fails, that's it. There are many guides on the internet on how to configure ffmpeg, for example: https://phoenixnap.com/kb/ffmpeg-windows

**Comment by zazazy** [comment]
> It seems that the problem is that you haven't properly installed ffmpeg or it isn't correctly set in your Windows PATH. You can check by typing ffmpeg into the terminal. If it fails, that's it. There are many guides on the internet on how to configure ffmpeg, for example: https://phoenixnap.com/kb/ffmpeg-windows
Do you have any ideas how to accelerate rendering process? Seems like not all resources of CPU or GPU involved.
![изображение](https://github.com/xaviviro/refacer/assets/32043698/65202152-e7b0-40e3-a574-4b39f4761c46)

**Comment by xaviviro** [comment]
Thank you for your comments, they help me continue making improvements. We've discussed the acceleration topic here: https://github.com/xaviviro/refacer/issues/5#issuecomment-1577471258
