### ISSUE TITLE
Antivirus detection 

### ISSUE THREAD

**Issue by gitihobo** [xaviviro/refacer#20]
site-packages\gradio\frpc_windows_amd64_v0.2 can be used by intruders to damage computer or personal data.

HEUR:NetTool.Win64.FRP.gen

Any way to resolve this?

**Comment by ooofest** [comment]
That's a generic heuristic and usually related to reputation more than anything truly suspicious, in my experience.

**Comment by gitihobo** [comment]
I see, it is possible to replace this riskware somehow? To increase security?

**Comment by xaviviro** [comment]
Thank you for your comments. This is an issue related to the Gradio package. You can find more information here: https://github.com/gradio-app/gradio/issues/3230
