### ISSUE TITLE
Could not locate zlibwapi.dll. Please make sure it is in your library path!

### ISSUE THREAD

**Issue by wu5shen** [xaviviro/refacer#35]
用GPU的时候一直提示这个：Could not locate zlibwapi.dll. Please make sure it is in your library path! 然后就自己报错退出了

**Comment by eliasts** [comment]
https://docs.nvidia.com/deeplearning/cudnn/install-guide/index.html#install-zlib-windows

You can copy this file somewhere and add it to the PATH or you could copy it to C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.x\bin folder
