### ISSUE TITLE
Option to swap to all faces?

### ISSUE THREAD

**Issue by G-force78** [xaviviro/refacer#72]
if not in the gradio UI is there a way to do it in the cli?
Very neat fork by the way , nice and quick and easy to use.

**Comment by ziptron** [comment]
You could always use the original (https://github.com/s0md3v/roop) and pass the --many-faces attribute. This worked for me when I tried it.

**Comment by G-force78** [comment]
> You could always use the original (https://github.com/s0md3v/roop) and pass the --many-faces attribute. This worked for me when I tried it.

Ive found swap-mukham is good for all features
